### ISSUE TITLE
I2C: WriteToRegister() and ReadFromRegister()

### ISSUE THREAD

**Issue by coolbix** [swharden/FtdiSharp#2]
A function read_from() which reads from a specific register seems to be implemented by writeThenRead(), which is excellent.
It would be good if we can have similar function such as 'write_to()' which writes to a specific register.
Thanks for the excellent code and document.

**Comment by swharden** [comment]
Hi @coolbix, thanks for the suggestion! When you say "register", are you talking about I2C devices that send data to a register? This is complicated because different I2C devices accept different number bytes. I guess we could have a few overloads that accept an address and one, two, or three bytes?

This is how it's done presently:
https://github.com/swharden/FtdiSharp/blob/146cfb80db8a3280a8bbae866464d098c1075aa9/src/FtdiSharpDemo/I2C_ADS1115DataLogger.cs#L51

Let me know what you think! Thanks
